import { Address, Citizen, Education, Email, Employment, Note, Phone } from "../types/citizen";

const generateId = () => `cit_${Math.random().toString(36).substring(2, 10)}`;

const calculateAge = (birthDate: string) => {
  const today = new Date();
  const birth = new Date(birthDate);
  let age = today.getFullYear() - birth.getFullYear();
  const monthDiff = today.getMonth() - birth.getMonth();
  if (monthDiff < 0 || (monthDiff === 0 && today.getDate() < birth.getDate())) {
    age--;
  }
  return age;
};

export const randomDate = (start: Date, end: Date) => {
  return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime())).toISOString().split("T")[0];
};

export const CITIZEN_MOCK_DATA: Citizen[] = [
  {
    id: "cit_001",
    createdAt: "2023-01-15T10:30:00Z",
    updatedAt: "2024-01-20T14:45:00Z",
    lastName: "Иванов",
    firstName: "Иван",
    middleName: "Иванович",
    fullName: "Иванов Иван Иванович",
    dateOfBirth: "1985-05-15",
    placeOfBirth: "г. Москва",
    gender: "male",
    age: calculateAge("1985-05-15"),
    inn: "770123456789",
    snils: "123-456-789 01",
    citizenship: "Российская Федерация",
    addresses: [
      {
        id: generateId(),
        type: "registration",
        country: "Россия",
        region: "Московская область",
        city: "Москва",
        district: "Центральный",
        street: "ул. Тверская",
        building: "15",
        apartment: "42",
        postalCode: "125009",
        isActual: true,
        comment: "Адрес регистрации",
      },
      {
        id: generateId(),
        type: "residence",
        country: "Россия",
        region: "Московская область",
        city: "Москва",
        district: "Замоскворечье",
        street: "ул. Пятницкая",
        building: "28",
        apartment: "105",
        postalCode: "115035",
        isActual: true,
        comment: "Фактическое проживание",
      },
    ] as Address[],
    phones: [
      { id: generateId(), type: "mobile", value: "+7 (999) 123-45-67", isPrimary: true, isVerified: true, comment: "Основной мобильный" },
      { id: generateId(), type: "work", value: "+7 (495) 987-65-43", isPrimary: false, isVerified: true, comment: "Рабочий телефон" },
    ] as Phone[],
    emails: [
      { id: generateId(), type: "personal", value: "ivan.ivanov@gmail.com", isPrimary: true, isVerified: true, comment: "Личная почта" },
      { id: generateId(), type: "work", value: "i.ivanov@company.ru", isPrimary: false, isVerified: true, comment: "Рабочая почта" },
    ] as Email[],
    preferredContactMethod: "phone",
    educationLevel: "master",
    educations: [
      {
        id: generateId(),
        level: "bachelor",
        institutionName: "Московский Государственный Университет",
        institutionType: "university",
        faculty: "Экономический",
        specialty: "Экономика предприятия",
        qualification: "Бакалавр экономики",
        startDate: "2003-09-01",
        endDate: "2007-06-30",
        documentNumber: "123456",
        documentDate: "2007-06-30",
        isCurrent: false,
        comment: "Диплом с отличием",
      },
      {
        id: generateId(),
        level: "master",
        institutionName: "Московский Государственный Университет",
        institutionType: "university",
        faculty: "Экономический",
        specialty: "Финансы и кредит",
        qualification: "Магистр экономики",
        startDate: "2007-09-01",
        endDate: "2009-06-30",
        documentNumber: "789012",
        documentDate: "2009-06-30",
        isCurrent: false,
        comment: "",
      },
    ] as Education[],
    employmentType: "full_time",
    employments: [
      {
        id: generateId(),
        organizationName: 'ООО "ТехноСтар"',
        organizationInn: "7701234567",
        position: "Менеджер по продажам",
        department: "Отдел продаж",
        employmentType: "full_time",
        startDate: "2010-03-01",
        endDate: "2015-12-31",
        isCurrent: false,
        salary: 80000,
        currency: "RUB",
        workSchedule: "full",
        address: "г. Москва, ул. Ленина, 10",
        supervisorName: "Петров П.П.",
        supervisorPhone: "+7 (495) 111-22-33",
        responsibilities: "Продажи, работа с клиентами",
        comment: "Уволился по собственному желанию",
      },
      {
        id: generateId(),
        organizationName: 'АО "Инновационные Решения"',
        organizationInn: "7709876543",
        position: "Старший менеджер",
        department: "Департамент развития",
        employmentType: "full_time",
        startDate: "2016-01-15",
        isCurrent: true,
        salary: 150000,
        currency: "RUB",
        workSchedule: "full",
        address: "г. Москва, Кутузовский пр., 45",
        supervisorName: "Сидоров С.С.",
        supervisorPhone: "+7 (495) 444-55-66",
        responsibilities: "Управление командой, стратегическое планирование",
        comment: "Текущее место работы",
      },
    ] as Employment[],
    currentOrganization: 'АО "Инновационные Решения"',
    currentPosition: "Старший менеджер",
    notes: [
      {
        id: generateId(),
        content: "Клиент премиум-сегмента, требует особого внимания",
        type: "important",
        createdById: "user_001",
        isPinned: true,
        tags: ["vip", "important"],
      },
      {
        id: generateId(),
        content: "Предпочитает общение в рабочее время с 10 до 18",
        type: "general",
        createdById: "user_002",
        isPinned: false,
        tags: ["contact"],
      },
    ] as Note[],
    maritalStatus: "married",
    hasChildren: true,
    childrenCount: 2,
    isPensioner: false,
    isDisabled: false,
    status: "active",
    category: "individual",
    isVIP: true,
    isBlacklisted: false,
    responsibleUserId: "user_001",
    responsibleUserName: "Менеджер Алексей",
    departmentName: "Отдел работы с клиентами",
    comment: "Лояльный клиент с 2015 года",
    tags: ["vip", "active", "premium"],
  },

  {
    id: "cit_002",
    createdAt: "2023-03-22T09:15:00Z",
    updatedAt: "2024-01-18T11:30:00Z",
    lastName: "Петрова",
    firstName: "Анна",
    middleName: "Сергеевна",
    fullName: "Петрова Анна Сергеевна",
    dateOfBirth: "1990-08-23",
    placeOfBirth: "г. Санкт-Петербург",
    gender: "female",
    age: calculateAge("1990-08-23"),
    inn: "780234567890",
    snils: "234-567-890 12",
    citizenship: "Российская Федерация",
    addresses: [
      {
        id: generateId(),
        type: "registration",
        country: "Россия",
        region: "Ленинградская область",
        city: "Санкт-Петербург",
        district: "Невский",
        street: "Невский проспект",
        building: "100",
        apartment: "25",
        postalCode: "191025",
        isActual: true,
        comment: "",
      },
    ] as Address[],
    phones: [{ id: generateId(), type: "mobile", value: "+7 (921) 234-56-78", isPrimary: true, isVerified: true, comment: "" }] as Phone[],
    emails: [{ id: generateId(), type: "personal", value: "anna.petrova@yandex.ru", isPrimary: true, isVerified: true, comment: "" }] as Email[],
    preferredContactMethod: "email",
    educationLevel: "bachelor",
    educations: [
      {
        id: generateId(),
        level: "bachelor",
        institutionName: "Санкт-Петербургский Государственный Университет",
        institutionType: "university",
        faculty: "Юридический",
        specialty: "Юриспруденция",
        qualification: "Бакалавр права",
        startDate: "2008-09-01",
        endDate: "2012-06-30",
        documentNumber: "345678",
        documentDate: "2012-06-30",
        isCurrent: false,
        comment: "",
      },
    ] as Education[],
    employmentType: "full_time",
    employments: [
      {
        id: generateId(),
        organizationName: 'Юридическая фирма "Право и Закон"',
        organizationInn: "7801234567",
        position: "Юрист",
        department: "Юридический отдел",
        employmentType: "full_time",
        startDate: "2013-02-01",
        isCurrent: true,
        salary: 120000,
        currency: "RUB",
        workSchedule: "full",
        address: "г. Санкт-Петербург, ул. Садовая, 50",
        supervisorName: "Иванов И.И.",
        supervisorPhone: "+7 (812) 333-44-55",
        responsibilities: "Консультирование, представительство в суде",
        comment: "",
      },
    ] as Employment[],
    currentOrganization: 'Юридическая фирма "Право и Закон"',
    currentPosition: "Юрист",
    notes: [
      { id: generateId(), content: "Предпочитает письменное общение", type: "general", createdById: "user_003", isPinned: false, tags: ["contact"] },
    ] as Note[],
    maritalStatus: "single",
    hasChildren: false,
    childrenCount: 0,
    isPensioner: false,
    isDisabled: false,
    status: "active",
    category: "individual",
    isVIP: false,
    isBlacklisted: false,
    responsibleUserId: "user_003",
    responsibleUserName: "Менеджер Ольга",
    departmentName: "Отдел работы с клиентами",
    comment: "",
    tags: ["active"],
  },

  {
    id: "cit_003",
    createdAt: "2022-11-10T14:20:00Z",
    updatedAt: "2024-01-15T16:00:00Z",
    lastName: "Смирнов",
    firstName: "Дмитрий",
    middleName: "Александрович",
    fullName: "Смирнов Дмитрий Александрович",
    dateOfBirth: "1978-12-05",
    placeOfBirth: "г. Екатеринбург",
    gender: "male",
    age: calculateAge("1978-12-05"),
    inn: "660345678901",
    snils: "345-678-901 23",
    citizenship: "Российская Федерация",
    addresses: [
      {
        id: generateId(),
        type: "registration",
        country: "Россия",
        region: "Свердловская область",
        city: "Екатеринбург",
        district: "Ленинский",
        street: "ул. Ленина",
        building: "52",
        apartment: "78",
        postalCode: "620014",
        isActual: true,
        comment: "",
      },
      {
        id: generateId(),
        type: "residence",
        country: "Россия",
        region: "Московская область",
        city: "Москва",
        district: "Пресненский",
        street: "ул. Красная Пресня",
        building: "10",
        apartment: "201",
        postalCode: "123022",
        isActual: true,
        comment: "Временное проживание в связи с работой",
      },
    ] as Address[],
    phones: [
      { id: generateId(), type: "mobile", value: "+7 (912) 345-67-89", isPrimary: true, isVerified: true, comment: "" },
      { id: generateId(), type: "home", value: "+7 (343) 555-66-77", isPrimary: false, isVerified: false, comment: "Домашний телефон" },
    ] as Phone[],
    emails: [{ id: generateId(), type: "personal", value: "d.smirnov@mail.ru", isPrimary: true, isVerified: true, comment: "" }] as Email[],
    preferredContactMethod: "phone",
    educationLevel: "vocational",
    educations: [
      {
        id: generateId(),
        level: "vocational",
        institutionName: "Екатеринбургский Технический Колледж",
        institutionType: "college",
        faculty: "",
        specialty: "Автомеханик",
        qualification: "Среднее специальное",
        startDate: "1995-09-01",
        endDate: "1998-06-30",
        documentNumber: "456789",
        documentDate: "1998-06-30",
        isCurrent: false,
        comment: "",
      },
    ] as Education[],
    employmentType: "self_employed",
    employments: [
      {
        id: generateId(),
        organizationName: "ИП Смирнов Д.А.",
        organizationInn: "660345678901",
        position: "Индивидуальный предприниматель",
        department: "",
        employmentType: "self_employed",
        startDate: "2010-01-01",
        isCurrent: true,
        salary: 200000,
        currency: "RUB",
        workSchedule: "full",
        address: "г. Екатеринбург, ул. Малышева, 100",
        supervisorName: "",
        supervisorPhone: "",
        responsibilities: "Ремонт автомобилей, техническое обслуживание",
        comment: "Владелец автосервиса",
      },
    ] as Employment[],
    currentOrganization: "ИП Смирнов Д.А.",
    currentPosition: "Индивидуальный предприниматель",
    notes: [
      {
        id: generateId(),
        content: "Владелец автосервиса, потенциальный партнер",
        type: "important",
        createdById: "user_004",
        isPinned: true,
        tags: ["partner", "business"],
      },
      {
        id: generateId(),
        content: "Переехал в Москву на временное проживание",
        type: "general",
        createdById: "user_004",
        isPinned: false,
        tags: ["relocation"],
      },
    ] as Note[],
    maritalStatus: "married",
    hasChildren: true,
    childrenCount: 3,
    isPensioner: false,
    isDisabled: false,
    status: "active",
    category: "entrepreneur",
    isVIP: false,
    isBlacklisted: false,
    responsibleUserId: "user_004",
    responsibleUserName: "Менеджер Игорь",
    departmentName: "Отдел работы с партнерами",
    comment: "Надежный партнер, работает с 2015 года",
    tags: ["entrepreneur", "partner", "active"],
  },

  {
    id: "cit_004",
    createdAt: "2023-06-05T08:45:00Z",
    updatedAt: "2024-01-10T10:15:00Z",
    lastName: "Козлова",
    firstName: "Елена",
    middleName: "Владимировна",
    fullName: "Козлова Елена Владимировна",
    dateOfBirth: "1965-03-18",
    placeOfBirth: "г. Казань",
    gender: "female",
    age: calculateAge("1965-03-18"),
    inn: "160456789012",
    snils: "456-789-012 34",
    citizenship: "Российская Федерация",
    addresses: [
      {
        id: generateId(),
        type: "registration",
        country: "Россия",
        region: "Республика Татарстан",
        city: "Казань",
        district: "Вахитовский",
        street: "ул. Баумана",
        building: "35",
        apartment: "12",
        postalCode: "420111",
        isActual: true,
        comment: "",
      },
    ] as Address[],
    phones: [{ id: generateId(), type: "mobile", value: "+7 (917) 456-78-90", isPrimary: true, isVerified: true, comment: "" }] as Phone[],
    emails: [
      { id: generateId(), type: "personal", value: "e.kozlova@mail.ru", isPrimary: true, isVerified: false, comment: "Требуется подтверждение" },
    ] as Email[],
    preferredContactMethod: "phone",
    educationLevel: "secondary",
    educations: [
      {
        id: generateId(),
        level: "secondary",
        institutionName: "Средняя школа №25",
        institutionType: "school",
        faculty: "",
        specialty: "",
        qualification: "Среднее образование",
        startDate: "1972-09-01",
        endDate: "1982-06-30",
        documentNumber: "567890",
        documentDate: "1982-06-30",
        isCurrent: false,
        comment: "",
      },
    ] as Education[],
    employmentType: "pensioner",
    employments: [
      {
        id: generateId(),
        organizationName: 'Завод "Татмаш"',
        organizationInn: "1601234567",
        position: "Бухгалтер",
        department: "Бухгалтерия",
        employmentType: "full_time",
        startDate: "1985-09-01",
        endDate: "2020-03-18",
        isCurrent: false,
        salary: 45000,
        currency: "RUB",
        workSchedule: "full",
        address: "г. Казань, ул. Декабристов, 100",
        supervisorName: "Петрова П.П.",
        supervisorPhone: "+7 (843) 222-33-44",
        responsibilities: "Ведение бухгалтерского учета",
        comment: "Вышла на пенсию",
      },
    ] as Employment[],
    currentOrganization: "",
    currentPosition: "Пенсионер",
    notes: [
      {
        id: generateId(),
        content: "Пенсионер, требуется особое внимание при общении",
        type: "important",
        createdById: "user_005",
        isPinned: true,
        tags: ["pensioner", "attention"],
      },
      {
        id: generateId(),
        content: "Предпочитает общение по телефону в дневное время",
        type: "general",
        createdById: "user_005",
        isPinned: false,
        tags: ["contact"],
      },
    ] as Note[],
    maritalStatus: "widowed",
    hasChildren: true,
    childrenCount: 2,
    isPensioner: true,
    isDisabled: true,
    disabilityGroup: "2",
    status: "active",
    category: "individual",
    isVIP: false,
    isBlacklisted: false,
    responsibleUserId: "user_005",
    responsibleUserName: "Менеджер Наталья",
    departmentName: "Отдел социальной поддержки",
    comment: "Нуждается в социальной поддержке",
    tags: ["pensioner", "disabled", "social"],
  },

  {
    id: "cit_005",
    createdAt: "2023-09-12T13:00:00Z",
    updatedAt: "2024-01-22T09:30:00Z",
    lastName: "Новиков",
    firstName: "Алексей",
    middleName: "Петрович",
    fullName: "Новиков Алексей Петрович",
    dateOfBirth: "1995-07-30",
    placeOfBirth: "г. Новосибирск",
    gender: "male",
    age: calculateAge("1995-07-30"),
    inn: "540567890123",
    snils: "567-890-123 45",
    citizenship: "Российская Федерация",
    addresses: [
      {
        id: generateId(),
        type: "registration",
        country: "Россия",
        region: "Новосибирская область",
        city: "Новосибирск",
        district: "Центральный",
        street: "Красный проспект",
        building: "82",
        apartment: "55",
        postalCode: "630007",
        isActual: true,
        comment: "",
      },
    ] as Address[],
    phones: [{ id: generateId(), type: "mobile", value: "+7 (913) 567-89-01", isPrimary: true, isVerified: true, comment: "" }] as Phone[],
    emails: [
      { id: generateId(), type: "personal", value: "a.novikov@gmail.com", isPrimary: true, isVerified: true, comment: "" },
      { id: generateId(), type: "work", value: "alexey.novikov@techcorp.ru", isPrimary: false, isVerified: true, comment: "" },
    ] as Email[],
    preferredContactMethod: "email",
    educationLevel: "master",
    educations: [
      {
        id: generateId(),
        level: "bachelor",
        institutionName: "Новосибирский Государственный Технический Университет",
        institutionType: "university",
        faculty: "Информационных технологий",
        specialty: "Программная инженерия",
        qualification: "Бакалавр",
        startDate: "2013-09-01",
        endDate: "2017-06-30",
        documentNumber: "678901",
        documentDate: "2017-06-30",
        isCurrent: false,
        comment: "",
      },
      {
        id: generateId(),
        level: "master",
        institutionName: "Новосибирский Государственный Университет",
        institutionType: "university",
        faculty: "Механико-математический",
        specialty: "Прикладная математика",
        qualification: "Магистр",
        startDate: "2017-09-01",
        endDate: "2019-06-30",
        documentNumber: "789012",
        documentDate: "2019-06-30",
        isCurrent: false,
        comment: "",
      },
    ] as Education[],
    employmentType: "full_time",
    employments: [
      {
        id: generateId(),
        organizationName: 'ООО "ТехКорп"',
        organizationInn: "5401234567",
        position: "Senior Developer",
        department: "Отдел разработки",
        employmentType: "full_time",
        startDate: "2019-08-01",
        isCurrent: true,
        salary: 250000,
        currency: "RUB",
        workSchedule: "remote",
        address: "г. Новосибирск, ул. Ленина, 20",
        supervisorName: "Волков В.В.",
        supervisorPhone: "+7 (383) 777-88-99",
        responsibilities: "Разработка backend, архитектура систем",
        comment: "Удаленная работа",
      },
    ] as Employment[],
    currentOrganization: 'ООО "ТехКорп"',
    currentPosition: "Senior Developer",
    notes: [
      {
        id: generateId(),
        content: "IT-специалист, работает удаленно",
        type: "general",
        createdById: "user_006",
        isPinned: false,
        tags: ["it", "remote"],
      },
    ] as Note[],
    maritalStatus: "single",
    hasChildren: false,
    childrenCount: 0,
    isPensioner: false,
    isDisabled: false,
    status: "active",
    category: "individual",
    isVIP: false,
    isBlacklisted: false,
    responsibleUserId: "user_006",
    responsibleUserName: "Менеджер Дмитрий",
    departmentName: "Отдел работы с клиентами",
    comment: "Молодой специалист, перспективный клиент",
    tags: ["it", "young", "active"],
  },

  {
    id: "cit_006",
    createdAt: "2023-02-18T11:20:00Z",
    updatedAt: "2024-01-19T15:45:00Z",
    lastName: "Васильева",
    firstName: "Мария",
    middleName: "Николаевна",
    fullName: "Васильева Мария Николаевна",
    dateOfBirth: "1988-11-12",
    placeOfBirth: "г. Нижний Новгород",
    gender: "female",
    age: calculateAge("1988-11-12"),
    inn: "520678901234",
    snils: "678-901-234 56",
    citizenship: "Российская Федерация",
    addresses: [
      {
        id: generateId(),
        type: "registration",
        country: "Россия",
        region: "Нижегородская область",
        city: "Нижний Новгород",
        district: "Приокский",
        street: "пр. Гагарина",
        building: "25",
        apartment: "88",
        postalCode: "603000",
        isActual: true,
        comment: "",
      },
    ] as Address[],
    phones: [{ id: generateId(), type: "mobile", value: "+7 (920) 678-90-12", isPrimary: true, isVerified: true, comment: "" }] as Phone[],
    emails: [{ id: generateId(), type: "personal", value: "m.vasileva@yandex.ru", isPrimary: true, isVerified: true, comment: "" }] as Email[],
    preferredContactMethod: "email",
    educationLevel: "bachelor",
    educations: [
      {
        id: generateId(),
        level: "bachelor",
        institutionName: "Нижегородский Государственный Университет",
        institutionType: "university",
        faculty: "Филологический",
        specialty: "Русская филология",
        qualification: "Бакалавр филологии",
        startDate: "2006-09-01",
        endDate: "2010-06-30",
        documentNumber: "890123",
        documentDate: "2010-06-30",
        isCurrent: false,
        comment: "",
      },
    ] as Education[],
    employmentType: "full_time",
    employments: [
      {
        id: generateId(),
        organizationName: 'Издательство "Книжный Мир"',
        organizationInn: "5201234567",
        position: "Редактор",
        department: "Редакционный отдел",
        employmentType: "full_time",
        startDate: "2011-03-01",
        isCurrent: true,
        salary: 65000,
        currency: "RUB",
        workSchedule: "full",
        address: "г. Нижний Новгород, ул. Большая Покровская, 15",
        supervisorName: "Соколов С.С.",
        supervisorPhone: "+7 (831) 444-55-66",
        responsibilities: "Редактирование книг, работа с авторами",
        comment: "",
      },
    ] as Employment[],
    currentOrganization: 'Издательство "Книжный Мир"',
    currentPosition: "Редактор",
    notes: [
      { id: generateId(), content: "Творческий подход к работе", type: "general", createdById: "user_007", isPinned: false, tags: ["creative"] },
    ] as Note[],
    maritalStatus: "married",
    hasChildren: true,
    childrenCount: 1,
    isPensioner: false,
    isDisabled: false,
    status: "active",
    category: "individual",
    isVIP: false,
    isBlacklisted: false,
    responsibleUserId: "user_007",
    responsibleUserName: "Менеджер Елена",
    departmentName: "Отдел работы с клиентами",
    comment: "",
    tags: ["active", "creative"],
  },

  {
    id: "cit_007",
    createdAt: "2023-04-25T14:30:00Z",
    updatedAt: "2024-01-21T12:00:00Z",
    lastName: "Морозов",
    firstName: "Сергей",
    middleName: "Владимирович",
    fullName: "Морозов Сергей Владимирович",
    dateOfBirth: "1982-02-28",
    placeOfBirth: "г. Челябинск",
    gender: "male",
    age: calculateAge("1982-02-28"),
    inn: "740789012345",
    snils: "789-012-345 67",
    citizenship: "Российская Федерация",
    addresses: [
      {
        id: generateId(),
        type: "registration",
        country: "Россия",
        region: "Челябинская область",
        city: "Челябинск",
        district: "Центральный",
        street: "ул. Кирова",
        building: "100",
        apartment: "45",
        postalCode: "454000",
        isActual: true,
        comment: "",
      },
    ] as Address[],
    phones: [
      { id: generateId(), type: "mobile", value: "+7 (902) 789-01-23", isPrimary: true, isVerified: true, comment: "" },
      { id: generateId(), type: "work", value: "+7 (351) 222-33-44", isPrimary: false, isVerified: true, comment: "" },
    ] as Phone[],
    emails: [{ id: generateId(), type: "personal", value: "s.morozov@mail.ru", isPrimary: true, isVerified: true, comment: "" }] as Email[],
    preferredContactMethod: "phone",
    educationLevel: "vocational",
    educations: [
      {
        id: generateId(),
        level: "vocational",
        institutionName: "Челябинский Строительный Колледж",
        institutionType: "college",
        faculty: "",
        specialty: "Строительство",
        qualification: "Среднее специальное",
        startDate: "1999-09-01",
        endDate: "2002-06-30",
        documentNumber: "901234",
        documentDate: "2002-06-30",
        isCurrent: false,
        comment: "",
      },
    ] as Education[],
    employmentType: "full_time",
    employments: [
      {
        id: generateId(),
        organizationName: 'ООО "СтройМастер"',
        organizationInn: "7401234567",
        position: "Прораб",
        department: "Строительный отдел",
        employmentType: "full_time",
        startDate: "2005-04-01",
        isCurrent: true,
        salary: 95000,
        currency: "RUB",
        workSchedule: "full",
        address: "г. Челябинск, ул. Труда, 50",
        supervisorName: "Козлов К.К.",
        supervisorPhone: "+7 (351) 555-66-77",
        responsibilities: "Руководство строительными работами",
        comment: "",
      },
    ] as Employment[],
    currentOrganization: 'ООО "СтройМастер"',
    currentPosition: "Прораб",
    notes: [
      {
        id: generateId(),
        content: "Опытный специалист, 20 лет в строительстве",
        type: "important",
        createdById: "user_008",
        isPinned: true,
        tags: ["experienced", "construction"],
      },
    ] as Note[],
    maritalStatus: "married",
    hasChildren: true,
    childrenCount: 2,
    isPensioner: false,
    isDisabled: false,
    status: "active",
    category: "individual",
    isVIP: false,
    isBlacklisted: false,
    responsibleUserId: "user_008",
    responsibleUserName: "Менеджер Андрей",
    departmentName: "Отдел работы с клиентами",
    comment: "Надежный клиент",
    tags: ["active", "construction"],
  },

  {
    id: "cit_008",
    createdAt: "2023-07-08T10:00:00Z",
    updatedAt: "2024-01-17T14:30:00Z",
    lastName: "Лебедева",
    firstName: "Ольга",
    middleName: "Дмитриевна",
    fullName: "Лебедева Ольга Дмитриевна",
    dateOfBirth: "1992-06-15",
    placeOfBirth: "г. Самара",
    gender: "female",
    age: calculateAge("1992-06-15"),
    inn: "630890123456",
    snils: "890-123-456 78",
    citizenship: "Российская Федерация",
    addresses: [
      {
        id: generateId(),
        type: "registration",
        country: "Россия",
        region: "Самарская область",
        city: "Самара",
        district: "Самарский",
        street: "ул. Куйбышева",
        building: "75",
        apartment: "30",
        postalCode: "443000",
        isActual: true,
        comment: "",
      },
    ] as Address[],
    phones: [{ id: generateId(), type: "mobile", value: "+7 (927) 890-12-34", isPrimary: true, isVerified: true, comment: "" }] as Phone[],
    emails: [
      { id: generateId(), type: "personal", value: "o.lebedeva@gmail.com", isPrimary: true, isVerified: true, comment: "" },
      { id: generateId(), type: "work", value: "olga.lebedeva@company.ru", isPrimary: false, isVerified: true, comment: "" },
    ] as Email[],
    preferredContactMethod: "email",
    educationLevel: "master",
    educations: [
      {
        id: generateId(),
        level: "bachelor",
        institutionName: "Самарский Государственный Университет",
        institutionType: "university",
        faculty: "Медицинский",
        specialty: "Лечебное дело",
        qualification: "Бакалавр медицины",
        startDate: "2010-09-01",
        endDate: "2014-06-30",
        documentNumber: "012345",
        documentDate: "2014-06-30",
        isCurrent: false,
        comment: "",
      },
      {
        id: generateId(),
        level: "master",
        institutionName: "Самарский Государственный Медицинский Университет",
        institutionType: "university",
        faculty: "Медицинский",
        specialty: "Терапия",
        qualification: "Магистр медицины",
        startDate: "2014-09-01",
        endDate: "2016-06-30",
        documentNumber: "123456",
        documentDate: "2016-06-30",
        isCurrent: false,
        comment: "",
      },
    ] as Education[],
    employmentType: "full_time",
    employments: [
      {
        id: generateId(),
        organizationName: "Городская Больница №5",
        organizationInn: "6301234567",
        position: "Врач-терапевт",
        department: "Терапевтическое отделение",
        employmentType: "full_time",
        startDate: "2016-09-01",
        isCurrent: true,
        salary: 85000,
        currency: "RUB",
        workSchedule: "shift",
        address: "г. Самара, ул. Ново-Садовая, 100",
        supervisorName: "Иванова И.И.",
        supervisorPhone: "+7 (846) 333-44-55",
        responsibilities: "Прием пациентов, диагностика",
        comment: "",
      },
    ] as Employment[],
    currentOrganization: "Городская Больница №5",
    currentPosition: "Врач-терапевт",
    notes: [
      {
        id: generateId(),
        content: "Медицинский работник, высокий уровень ответственности",
        type: "important",
        createdById: "user_009",
        isPinned: true,
        tags: ["medical", "important"],
      },
    ] as Note[],
    maritalStatus: "single",
    hasChildren: false,
    childrenCount: 0,
    isPensioner: false,
    isDisabled: false,
    status: "active",
    category: "individual",
    isVIP: false,
    isBlacklisted: false,
    responsibleUserId: "user_009",
    responsibleUserName: "Менеджер Сергей",
    departmentName: "Отдел работы с клиентами",
    comment: "",
    tags: ["medical", "active"],
  },

  {
    id: "cit_009",
    createdAt: "2023-05-14T09:45:00Z",
    updatedAt: "2024-01-16T11:20:00Z",
    lastName: "Ковалев",
    firstName: "Андрей",
    middleName: "Михайлович",
    fullName: "Ковалев Андрей Михайлович",
    dateOfBirth: "1975-09-20",
    placeOfBirth: "г. Ростов-на-Дону",
    gender: "male",
    age: calculateAge("1975-09-20"),
    inn: "610901234567",
    snils: "901-234-567 89",
    citizenship: "Российская Федерация",
    addresses: [
      {
        id: generateId(),
        type: "registration",
        country: "Россия",
        region: "Ростовская область",
        city: "Ростов-на-Дону",
        district: "Ленинский",
        street: "ул. Большая Садовая",
        building: "120",
        apartment: "60",
        postalCode: "344000",
        isActual: true,
        comment: "",
      },
    ] as Address[],
    phones: [{ id: generateId(), type: "mobile", value: "+7 (918) 901-23-45", isPrimary: true, isVerified: true, comment: "" }] as Phone[],
    emails: [{ id: generateId(), type: "personal", value: "a.kovalev@yandex.ru", isPrimary: true, isVerified: true, comment: "" }] as Email[],
    preferredContactMethod: "phone",
    educationLevel: "bachelor",
    educations: [
      {
        id: generateId(),
        level: "bachelor",
        institutionName: "Ростовский Государственный Университет",
        institutionType: "university",
        faculty: "Экономический",
        specialty: "Бухгалтерский учет",
        qualification: "Бакалавр экономики",
        startDate: "1993-09-01",
        endDate: "1997-06-30",
        documentNumber: "234567",
        documentDate: "1997-06-30",
        isCurrent: false,
        comment: "",
      },
    ] as Education[],
    employmentType: "full_time",
    employments: [
      {
        id: generateId(),
        organizationName: 'ООО "ЮгАгро"',
        organizationInn: "6101234567",
        position: "Главный бухгалтер",
        department: "Бухгалтерия",
        employmentType: "full_time",
        startDate: "2000-01-15",
        isCurrent: true,
        salary: 110000,
        currency: "RUB",
        workSchedule: "full",
        address: "г. Ростов-на-Дону, пр. Ворошиловский, 50",
        supervisorName: "Петров П.П.",
        supervisorPhone: "+7 (863) 222-33-44",
        responsibilities: "Ведение бухгалтерии, отчетность",
        comment: "",
      },
    ] as Employment[],
    currentOrganization: 'ООО "ЮгАгро"',
    currentPosition: "Главный бухгалтер",
    notes: [
      {
        id: generateId(),
        content: "Опытный бухгалтер, 25 лет стажа",
        type: "general",
        createdById: "user_010",
        isPinned: false,
        tags: ["accounting", "experienced"],
      },
    ] as Note[],
    maritalStatus: "married",
    hasChildren: true,
    childrenCount: 2,
    isPensioner: false,
    isDisabled: false,
    status: "active",
    category: "individual",
    isVIP: false,
    isBlacklisted: false,
    responsibleUserId: "user_010",
    responsibleUserName: "Менеджер Анна",
    departmentName: "Отдел работы с клиентами",
    comment: "",
    tags: ["active", "accounting"],
  },

  {
    id: "cit_010",
    createdAt: "2023-08-20T16:15:00Z",
    updatedAt: "2024-01-14T10:00:00Z",
    lastName: "Попова",
    firstName: "Наталья",
    middleName: "Алексеевна",
    fullName: "Попова Наталья Алексеевна",
    dateOfBirth: "1998-04-05",
    placeOfBirth: "г. Воронеж",
    gender: "female",
    age: calculateAge("1998-04-05"),
    inn: "360012345678",
    snils: "012-345-678 90",
    citizenship: "Российская Федерация",
    addresses: [
      {
        id: generateId(),
        type: "registration",
        country: "Россия",
        region: "Воронежская область",
        city: "Воронеж",
        district: "Центральный",
        street: "пр. Революции",
        building: "45",
        apartment: "18",
        postalCode: "394000",
        isActual: true,
        comment: "",
      },
    ] as Address[],
    phones: [{ id: generateId(), type: "mobile", value: "+7 (920) 012-34-56", isPrimary: true, isVerified: true, comment: "" }] as Phone[],
    emails: [{ id: generateId(), type: "personal", value: "n.popova@gmail.com", isPrimary: true, isVerified: true, comment: "" }] as Email[],
    preferredContactMethod: "messenger",
    educationLevel: "bachelor",
    educations: [
      {
        id: generateId(),
        level: "bachelor",
        institutionName: "Воронежский Государственный Университет",
        institutionType: "university",
        faculty: "Журналистики",
        specialty: "Журналистика",
        qualification: "Бакалавр",
        startDate: "2016-09-01",
        endDate: "2020-06-30",
        documentNumber: "345678",
        documentDate: "2020-06-30",
        isCurrent: false,
        comment: "",
      },
    ] as Education[],
    employmentType: "full_time",
    employments: [
      {
        id: generateId(),
        organizationName: 'Издательский дом "Комсомольская Правда"',
        organizationInn: "3601234567",
        position: "Журналист",
        department: "Редакция",
        employmentType: "full_time",
        startDate: "2020-09-01",
        isCurrent: true,
        salary: 55000,
        currency: "RUB",
        workSchedule: "full",
        address: "г. Воронеж, ул. Плехановская, 20",
        supervisorName: "Смирнов С.С.",
        supervisorPhone: "+7 (473) 444-55-66",
        responsibilities: "Написание статей, интервью",
        comment: "",
      },
    ] as Employment[],
    currentOrganization: 'Издательский дом "Комсомольская Правда"',
    currentPosition: "Журналист",
    notes: [
      {
        id: generateId(),
        content: "Молодой специалист, перспективный журналист",
        type: "general",
        createdById: "user_011",
        isPinned: false,
        tags: ["journalism", "young"],
      },
    ] as Note[],
    maritalStatus: "single",
    hasChildren: false,
    childrenCount: 0,
    isPensioner: false,
    isDisabled: false,
    status: "active",
    category: "individual",
    isVIP: false,
    isBlacklisted: false,
    responsibleUserId: "user_011",
    responsibleUserName: "Менеджер Виктор",
    departmentName: "Отдел работы с клиентами",
    comment: "",
    tags: ["young", "active", "journalism"],
  },

  {
    id: "cit_011",
    createdAt: "2023-01-28T12:30:00Z",
    updatedAt: "2024-01-13T15:45:00Z",
    lastName: "Соколов",
    firstName: "Михаил",
    middleName: "Юрьевич",
    fullName: "Соколов Михаил Юрьевич",
    dateOfBirth: "1970-01-10",
    placeOfBirth: "г. Уфа",
    gender: "male",
    age: calculateAge("1970-01-10"),
    inn: "020123456789",
    snils: "123-456-789 02",
    citizenship: "Российская Федерация",
    addresses: [
      {
        id: generateId(),
        type: "registration",
        country: "Россия",
        region: "Республика Башкортостан",
        city: "Уфа",
        district: "Кировский",
        street: "ул. Ленина",
        building: "30",
        apartment: "15",
        postalCode: "450000",
        isActual: true,
        comment: "",
      },
    ] as Address[],
    phones: [{ id: generateId(), type: "mobile", value: "+7 (917) 123-45-67", isPrimary: true, isVerified: true, comment: "" }] as Phone[],
    emails: [{ id: generateId(), type: "personal", value: "m.sokolov@mail.ru", isPrimary: true, isVerified: false, comment: "" }] as Email[],
    preferredContactMethod: "phone",
    educationLevel: "secondary",
    educations: [
      {
        id: generateId(),
        level: "secondary",
        institutionName: "Средняя школа №10",
        institutionType: "school",
        faculty: "",
        specialty: "",
        qualification: "Среднее образование",
        startDate: "1977-09-01",
        endDate: "1987-06-30",
        documentNumber: "456789",
        documentDate: "1987-06-30",
        isCurrent: false,
        comment: "",
      },
    ] as Education[],
    employmentType: "pensioner",
    employments: [
      {
        id: generateId(),
        organizationName: 'Завод "УфаСталь"',
        organizationInn: "0201234567",
        position: "Слесарь",
        department: "Производственный цех",
        employmentType: "full_time",
        startDate: "1988-03-01",
        endDate: "2015-01-10",
        isCurrent: false,
        salary: 35000,
        currency: "RUB",
        workSchedule: "full",
        address: "г. Уфа, ул. Менделеева, 100",
        supervisorName: "Иванов И.И.",
        supervisorPhone: "+7 (347) 555-66-77",
        responsibilities: "Ремонт оборудования",
        comment: "Вышел на пенсию по возрасту",
      },
    ] as Employment[],
    currentOrganization: "",
    currentPosition: "Пенсионер",
    notes: [
      {
        id: generateId(),
        content: "Пенсионер, ветеран труда",
        type: "important",
        createdById: "user_012",
        isPinned: true,
        tags: ["pensioner", "veteran"],
      },
    ] as Note[],
    maritalStatus: "married",
    hasChildren: true,
    childrenCount: 2,
    isPensioner: true,
    isDisabled: false,
    status: "active",
    category: "individual",
    isVIP: false,
    isBlacklisted: false,
    responsibleUserId: "user_012",
    responsibleUserName: "Менеджер Юлия",
    departmentName: "Отдел социальной поддержки",
    comment: "Ветеран труда, 40 лет стажа",
    tags: ["pensioner", "veteran", "social"],
  },

  {
    id: "cit_012",
    createdAt: "2023-10-05T08:00:00Z",
    updatedAt: "2024-01-23T09:15:00Z",
    lastName: "Федорова",
    firstName: "Екатерина",
    middleName: "Павловна",
    fullName: "Федорова Екатерина Павловна",
    dateOfBirth: "1993-12-25",
    placeOfBirth: "г. Пермь",
    gender: "female",
    age: calculateAge("1993-12-25"),
    inn: "590234567890",
    snils: "234-567-890 13",
    citizenship: "Российская Федерация",
    addresses: [
      {
        id: generateId(),
        type: "registration",
        country: "Россия",
        region: "Пермский край",
        city: "Пермь",
        district: "Дзержинский",
        street: "ул. Комсомольская",
        building: "65",
        apartment: "40",
        postalCode: "614000",
        isActual: true,
        comment: "",
      },
    ] as Address[],
    phones: [{ id: generateId(), type: "mobile", value: "+7 (902) 234-56-78", isPrimary: true, isVerified: true, comment: "" }] as Phone[],
    emails: [{ id: generateId(), type: "personal", value: "e.fedorova@yandex.ru", isPrimary: true, isVerified: true, comment: "" }] as Email[],
    preferredContactMethod: "email",
    educationLevel: "master",
    educations: [
      {
        id: generateId(),
        level: "bachelor",
        institutionName: "Пермский Государственный Университет",
        institutionType: "university",
        faculty: "Педагогический",
        specialty: "Педагогика",
        qualification: "Бакалавр педагогики",
        startDate: "2011-09-01",
        endDate: "2015-06-30",
        documentNumber: "567890",
        documentDate: "2015-06-30",
        isCurrent: false,
        comment: "",
      },
      {
        id: generateId(),
        level: "master",
        institutionName: "Пермский Государственный Университет",
        institutionType: "university",
        faculty: "Педагогический",
        specialty: "Управление образованием",
        qualification: "Магистр педагогики",
        startDate: "2015-09-01",
        endDate: "2017-06-30",
        documentNumber: "678901",
        documentDate: "2017-06-30",
        isCurrent: false,
        comment: "",
      },
    ] as Education[],
    employmentType: "full_time",
    employments: [
      {
        id: generateId(),
        organizationName: "Школа №50",
        organizationInn: "5901234567",
        position: "Учитель математики",
        department: "Учебная часть",
        employmentType: "full_time",
        startDate: "2017-09-01",
        isCurrent: true,
        salary: 45000,
        currency: "RUB",
        workSchedule: "full",
        address: "г. Пермь, ул. Ленина, 75",
        supervisorName: "Петрова П.П.",
        supervisorPhone: "+7 (342) 333-44-55",
        responsibilities: "Преподавание математики",
        comment: "",
      },
    ] as Employment[],
    currentOrganization: "Школа №50",
    currentPosition: "Учитель математики",
    notes: [
      {
        id: generateId(),
        content: "Педагог, работает в школе",
        type: "general",
        createdById: "user_013",
        isPinned: false,
        tags: ["teacher", "education"],
      },
    ] as Note[],
    maritalStatus: "married",
    hasChildren: true,
    childrenCount: 1,
    isPensioner: false,
    isDisabled: false,
    status: "active",
    category: "individual",
    isVIP: false,
    isBlacklisted: false,
    responsibleUserId: "user_013",
    responsibleUserName: "Менеджер Мария",
    departmentName: "Отдел работы с клиентами",
    comment: "",
    tags: ["teacher", "active", "education"],
  },

  {
    id: "cit_013",
    createdAt: "2023-03-10T13:45:00Z",
    updatedAt: "2024-01-12T16:30:00Z",
    lastName: "Орлов",
    firstName: "Виктор",
    middleName: "Андреевич",
    fullName: "Орлов Виктор Андреевич",
    dateOfBirth: "1987-07-18",
    placeOfBirth: "г. Волгоград",
    gender: "male",
    age: calculateAge("1987-07-18"),
    inn: "340345678901",
    snils: "345-678-901 24",
    citizenship: "Российская Федерация",
    addresses: [
      {
        id: generateId(),
        type: "registration",
        country: "Россия",
        region: "Волгоградская область",
        city: "Волгоград",
        district: "Центральный",
        street: "ул. Мира",
        building: "80",
        apartment: "55",
        postalCode: "400000",
        isActual: true,
        comment: "",
      },
    ] as Address[],
    phones: [{ id: generateId(), type: "mobile", value: "+7 (903) 345-67-89", isPrimary: true, isVerified: true, comment: "" }] as Phone[],
    emails: [{ id: generateId(), type: "personal", value: "v.orlov@gmail.com", isPrimary: true, isVerified: true, comment: "" }] as Email[],
    preferredContactMethod: "phone",
    educationLevel: "bachelor",
    educations: [
      {
        id: generateId(),
        level: "bachelor",
        institutionName: "Волгоградский Государственный Университет",
        institutionType: "university",
        faculty: "Юридический",
        specialty: "Правоохранительная деятельность",
        qualification: "Бакалавр права",
        startDate: "2005-09-01",
        endDate: "2009-06-30",
        documentNumber: "789012",
        documentDate: "2009-06-30",
        isCurrent: false,
        comment: "",
      },
    ] as Education[],
    employmentType: "full_time",
    employments: [
      {
        id: generateId(),
        organizationName: "УМВД России по Волгоградской области",
        organizationInn: "3401234567",
        position: "Следователь",
        department: "Следственный отдел",
        employmentType: "full_time",
        startDate: "2010-02-01",
        isCurrent: true,
        salary: 75000,
        currency: "RUB",
        workSchedule: "full",
        address: "г. Волгоград, ул. Комсомольская, 20",
        supervisorName: "Сидоров С.С.",
        supervisorPhone: "+7 (8442) 222-33-44",
        responsibilities: "Расследование преступлений",
        comment: "",
      },
    ] as Employment[],
    currentOrganization: "УМВД России по Волгоградской области",
    currentPosition: "Следователь",
    notes: [
      {
        id: generateId(),
        content: "Сотрудник правоохранительных органов",
        type: "important",
        createdById: "user_014",
        isPinned: true,
        tags: ["police", "important"],
      },
    ] as Note[],
    maritalStatus: "married",
    hasChildren: true,
    childrenCount: 2,
    isPensioner: false,
    isDisabled: false,
    status: "active",
    category: "individual",
    isVIP: false,
    isBlacklisted: false,
    responsibleUserId: "user_014",
    responsibleUserName: "Менеджер Ольга",
    departmentName: "Отдел работы с клиентами",
    comment: "",
    tags: ["police", "active"],
  },

  {
    id: "cit_014",
    createdAt: "2023-06-18T11:00:00Z",
    updatedAt: "2024-01-11T14:00:00Z",
    lastName: "Зайцева",
    firstName: "Ирина",
    middleName: "Борисовна",
    fullName: "Зайцева Ирина Борисовна",
    dateOfBirth: "1980-03-22",
    placeOfBirth: "г. Красноярск",
    gender: "female",
    age: calculateAge("1980-03-22"),
    inn: "240456789012",
    snils: "456-789-012 35",
    citizenship: "Российская Федерация",
    addresses: [
      {
        id: generateId(),
        type: "registration",
        country: "Россия",
        region: "Красноярский край",
        city: "Красноярск",
        district: "Центральный",
        street: "пр. Мира",
        building: "90",
        apartment: "70",
        postalCode: "660000",
        isActual: true,
        comment: "",
      },
    ] as Address[],
    phones: [{ id: generateId(), type: "mobile", value: "+7 (913) 456-78-90", isPrimary: true, isVerified: true, comment: "" }] as Phone[],
    emails: [{ id: generateId(), type: "personal", value: "i.zaytseva@mail.ru", isPrimary: true, isVerified: true, comment: "" }] as Email[],
    preferredContactMethod: "phone",
    educationLevel: "vocational",
    educations: [
      {
        id: generateId(),
        level: "vocational",
        institutionName: "Красноярский Торговый Колледж",
        institutionType: "college",
        faculty: "",
        specialty: "Товароведение",
        qualification: "Среднее специальное",
        startDate: "1997-09-01",
        endDate: "2000-06-30",
        documentNumber: "890123",
        documentDate: "2000-06-30",
        isCurrent: false,
        comment: "",
      },
    ] as Education[],
    employmentType: "full_time",
    employments: [
      {
        id: generateId(),
        organizationName: 'Торговая сеть "Пятерочка"',
        organizationInn: "2401234567",
        position: "Управляющая магазином",
        department: "Розничная торговля",
        employmentType: "full_time",
        startDate: "2005-06-01",
        isCurrent: true,
        salary: 70000,
        currency: "RUB",
        workSchedule: "shift",
        address: "г. Красноярск, ул. Ленина, 150",
        supervisorName: "Козлов К.К.",
        supervisorPhone: "+7 (391) 444-55-66",
        responsibilities: "Управление магазином, контроль персонала",
        comment: "",
      },
    ] as Employment[],
    currentOrganization: 'Торговая сеть "Пятерочка"',
    currentPosition: "Управляющая магазином",
    notes: [
      {
        id: generateId(),
        content: "Опытный руководитель в ритейле",
        type: "general",
        createdById: "user_015",
        isPinned: false,
        tags: ["retail", "manager"],
      },
    ] as Note[],
    maritalStatus: "divorced",
    hasChildren: true,
    childrenCount: 1,
    isPensioner: false,
    isDisabled: false,
    status: "active",
    category: "individual",
    isVIP: false,
    isBlacklisted: false,
    responsibleUserId: "user_015",
    responsibleUserName: "Менеджер Татьяна",
    departmentName: "Отдел работы с клиентами",
    comment: "",
    tags: ["retail", "active", "manager"],
  },

  {
    id: "cit_015",
    createdAt: "2023-09-25T15:30:00Z",
    updatedAt: "2024-01-24T10:45:00Z",
    lastName: "Павлов",
    firstName: "Константин",
    middleName: "Сергеевич",
    fullName: "Павлов Константин Сергеевич",
    dateOfBirth: "1996-10-08",
    placeOfBirth: "г. Омск",
    gender: "male",
    age: calculateAge("1996-10-08"),
    inn: "550567890123",
    snils: "567-890-123 46",
    citizenship: "Российская Федерация",
    addresses: [
      {
        id: generateId(),
        type: "registration",
        country: "Россия",
        region: "Омская область",
        city: "Омск",
        district: "Центральный",
        street: "ул. Ленина",
        building: "35",
        apartment: "22",
        postalCode: "644000",
        isActual: true,
        comment: "",
      },
    ] as Address[],
    phones: [{ id: generateId(), type: "mobile", value: "+7 (904) 567-89-01", isPrimary: true, isVerified: true, comment: "" }] as Phone[],
    emails: [{ id: generateId(), type: "personal", value: "k.pavlov@gmail.com", isPrimary: true, isVerified: true, comment: "" }] as Email[],
    preferredContactMethod: "messenger",
    educationLevel: "bachelor",
    educations: [
      {
        id: generateId(),
        level: "bachelor",
        institutionName: "Омский Государственный Технический Университет",
        institutionType: "university",
        faculty: "Информационных технологий",
        specialty: "Информатика",
        qualification: "Бакалавр",
        startDate: "2014-09-01",
        endDate: "2018-06-30",
        documentNumber: "901234",
        documentDate: "2018-06-30",
        isCurrent: false,
        comment: "",
      },
    ] as Education[],
    employmentType: "full_time",
    employments: [
      {
        id: generateId(),
        organizationName: 'ООО "АйтиСофт"',
        organizationInn: "5501234567",
        position: "Frontend Developer",
        department: "Отдел разработки",
        employmentType: "full_time",
        startDate: "2018-09-01",
        isCurrent: true,
        salary: 120000,
        currency: "RUB",
        workSchedule: "remote",
        address: "г. Омск, ул. Маршала Жукова, 50",
        supervisorName: "Волков В.В.",
        supervisorPhone: "+7 (3812) 555-66-77",
        responsibilities: "Разработка веб-интерфейсов",
        comment: "Удаленная работа",
      },
    ] as Employment[],
    currentOrganization: 'ООО "АйтиСофт"',
    currentPosition: "Frontend Developer",
    notes: [
      {
        id: generateId(),
        content: "IT-специалист, работает удаленно из Омска",
        type: "general",
        createdById: "user_016",
        isPinned: false,
        tags: ["it", "remote"],
      },
    ] as Note[],
    maritalStatus: "single",
    hasChildren: false,
    childrenCount: 0,
    isPensioner: false,
    isDisabled: false,
    status: "active",
    category: "individual",
    isVIP: false,
    isBlacklisted: false,
    responsibleUserId: "user_016",
    responsibleUserName: "Менеджер Игорь",
    departmentName: "Отдел работы с клиентами",
    comment: "",
    tags: ["it", "young", "active", "remote"],
  },

  {
    id: "cit_016",
    createdAt: "2023-04-12T10:20:00Z",
    updatedAt: "2024-01-09T13:00:00Z",
    lastName: "Степанова",
    firstName: "Светлана",
    middleName: "Игоревна",
    fullName: "Степанова Светлана Игоревна",
    dateOfBirth: "1983-05-30",
    placeOfBirth: "г. Саратов",
    gender: "female",
    age: calculateAge("1983-05-30"),
    inn: "640678901234",
    snils: "678-901-234 57",
    citizenship: "Российская Федерация",
    addresses: [
      {
        id: generateId(),
        type: "registration",
        country: "Россия",
        region: "Саратовская область",
        city: "Саратов",
        district: "Фрунзенский",
        street: "ул. Чапаева",
        building: "55",
        apartment: "35",
        postalCode: "410000",
        isActual: true,
        comment: "",
      },
    ] as Address[],
    phones: [{ id: generateId(), type: "mobile", value: "+7 (905) 678-90-12", isPrimary: true, isVerified: true, comment: "" }] as Phone[],
    emails: [{ id: generateId(), type: "personal", value: "s.stepanova@yandex.ru", isPrimary: true, isVerified: true, comment: "" }] as Email[],
    preferredContactMethod: "phone",
    educationLevel: "bachelor",
    educations: [
      {
        id: generateId(),
        level: "bachelor",
        institutionName: "Саратовский Государственный Университет",
        institutionType: "university",
        faculty: "Экономический",
        specialty: "Маркетинг",
        qualification: "Бакалавр экономики",
        startDate: "2001-09-01",
        endDate: "2005-06-30",
        documentNumber: "012345",
        documentDate: "2005-06-30",
        isCurrent: false,
        comment: "",
      },
    ] as Education[],
    employmentType: "full_time",
    employments: [
      {
        id: generateId(),
        organizationName: 'ООО "МаркетПлюс"',
        organizationInn: "6401234567",
        position: "Маркетолог",
        department: "Отдел маркетинга",
        employmentType: "full_time",
        startDate: "2008-04-01",
        isCurrent: true,
        salary: 65000,
        currency: "RUB",
        workSchedule: "full",
        address: "г. Саратов, ул. Московская, 80",
        supervisorName: "Петров П.П.",
        supervisorPhone: "+7 (8452) 333-44-55",
        responsibilities: "Маркетинговые исследования, реклама",
        comment: "",
      },
    ] as Employment[],
    currentOrganization: 'ООО "МаркетПлюс"',
    currentPosition: "Маркетолог",
    notes: [
      { id: generateId(), content: "Специалист по маркетингу", type: "general", createdById: "user_017", isPinned: false, tags: ["marketing"] },
    ] as Note[],
    maritalStatus: "married",
    hasChildren: true,
    childrenCount: 2,
    isPensioner: false,
    isDisabled: false,
    status: "active",
    category: "individual",
    isVIP: false,
    isBlacklisted: false,
    responsibleUserId: "user_017",
    responsibleUserName: "Менеджер Анна",
    departmentName: "Отдел работы с клиентами",
    comment: "",
    tags: ["marketing", "active"],
  },

  {
    id: "cit_017",
    createdAt: "2023-07-30T14:00:00Z",
    updatedAt: "2024-01-08T11:30:00Z",
    lastName: "Николаев",
    firstName: "Александр",
    middleName: "Васильевич",
    fullName: "Николаев Александр Васильевич",
    dateOfBirth: "1968-08-14",
    placeOfBirth: "г. Тюмень",
    gender: "male",
    age: calculateAge("1968-08-14"),
    inn: "720789012345",
    snils: "789-012-345 68",
    citizenship: "Российская Федерация",
    addresses: [
      {
        id: generateId(),
        type: "registration",
        country: "Россия",
        region: "Тюменская область",
        city: "Тюмень",
        district: "Центральный",
        street: "ул. Республики",
        building: "70",
        apartment: "50",
        postalCode: "625000",
        isActual: true,
        comment: "",
      },
    ] as Address[],
    phones: [{ id: generateId(), type: "mobile", value: "+7 (906) 789-01-23", isPrimary: true, isVerified: true, comment: "" }] as Phone[],
    emails: [{ id: generateId(), type: "personal", value: "a.nikolaev@mail.ru", isPrimary: true, isVerified: false, comment: "" }] as Email[],
    preferredContactMethod: "phone",
    educationLevel: "vocational",
    educations: [
      {
        id: generateId(),
        level: "vocational",
        institutionName: "Тюменский Нефтяной Колледж",
        institutionType: "college",
        faculty: "",
        specialty: "Бурение нефтяных скважин",
        qualification: "Среднее специальное",
        startDate: "1985-09-01",
        endDate: "1988-06-30",
        documentNumber: "123456",
        documentDate: "1988-06-30",
        isCurrent: false,
        comment: "",
      },
    ] as Education[],
    employmentType: "pensioner",
    employments: [
      {
        id: generateId(),
        organizationName: 'ООО "ТюменьНефть"',
        organizationInn: "7201234567",
        position: "Бурильщик",
        department: "Буровая бригада",
        employmentType: "full_time",
        startDate: "1988-09-01",
        endDate: "2018-08-14",
        isCurrent: false,
        salary: 120000,
        currency: "RUB",
        workSchedule: "shift",
        address: "г. Тюмень, ул. Мельникайте, 100",
        supervisorName: "Иванов И.И.",
        supervisorPhone: "+7 (3452) 444-55-66",
        responsibilities: "Бурение скважин",
        comment: "Вышел на пенсию по возрасту",
      },
    ] as Employment[],
    currentOrganization: "",
    currentPosition: "Пенсионер",
    notes: [
      {
        id: generateId(),
        content: "Пенсионер, ветеран нефтегазовой отрасли",
        type: "important",
        createdById: "user_018",
        isPinned: true,
        tags: ["pensioner", "oil", "veteran"],
      },
    ] as Note[],
    maritalStatus: "married",
    hasChildren: true,
    childrenCount: 2,
    isPensioner: true,
    isDisabled: false,
    status: "active",
    category: "individual",
    isVIP: false,
    isBlacklisted: false,
    responsibleUserId: "user_018",
    responsibleUserName: "Менеджер Сергей",
    departmentName: "Отдел социальной поддержки",
    comment: "Ветеран труда, 30 лет в нефтегазовой отрасли",
    tags: ["pensioner", "veteran", "oil"],
  },

  {
    id: "cit_018",
    createdAt: "2023-11-08T09:30:00Z",
    updatedAt: "2024-01-25T15:00:00Z",
    lastName: "Алексеева",
    firstName: "Юлия",
    middleName: "Михайловна",
    fullName: "Алексеева Юлия Михайловна",
    dateOfBirth: "1991-02-14",
    placeOfBirth: "г. Иркутск",
    gender: "female",
    age: calculateAge("1991-02-14"),
    inn: "380890123456",
    snils: "890-123-456 79",
    citizenship: "Российская Федерация",
    addresses: [
      {
        id: generateId(),
        type: "registration",
        country: "Россия",
        region: "Иркутская область",
        city: "Иркутск",
        district: "Октябрьский",
        street: "ул. Карла Маркса",
        building: "40",
        apartment: "28",
        postalCode: "664000",
        isActual: true,
        comment: "",
      },
    ] as Address[],
    phones: [{ id: generateId(), type: "mobile", value: "+7 (907) 890-12-34", isPrimary: true, isVerified: true, comment: "" }] as Phone[],
    emails: [{ id: generateId(), type: "personal", value: "y.alekseeva@gmail.com", isPrimary: true, isVerified: true, comment: "" }] as Email[],
    preferredContactMethod: "email",
    educationLevel: "master",
    educations: [
      {
        id: generateId(),
        level: "bachelor",
        institutionName: "Иркутский Государственный Университет",
        institutionType: "university",
        faculty: "Биологический",
        specialty: "Биология",
        qualification: "Бакалавр биологии",
        startDate: "2009-09-01",
        endDate: "2013-06-30",
        documentNumber: "234567",
        documentDate: "2013-06-30",
        isCurrent: false,
        comment: "",
      },
      {
        id: generateId(),
        level: "master",
        institutionName: "Иркутский Государственный Университет",
        institutionType: "university",
        faculty: "Биологический",
        specialty: "Экология",
        qualification: "Магистр биологии",
        startDate: "2013-09-01",
        endDate: "2015-06-30",
        documentNumber: "345678",
        documentDate: "2015-06-30",
        isCurrent: false,
        comment: "",
      },
    ] as Education[],
    employmentType: "full_time",
    employments: [
      {
        id: generateId(),
        organizationName: "Научно-исследовательский институт",
        organizationInn: "3801234567",
        position: "Научный сотрудник",
        department: "Лаборатория экологии",
        employmentType: "full_time",
        startDate: "2015-09-01",
        isCurrent: true,
        salary: 55000,
        currency: "RUB",
        workSchedule: "full",
        address: "г. Иркутск, ул. Лермонтова, 128",
        supervisorName: "Сидоров С.С.",
        supervisorPhone: "+7 (3952) 555-66-77",
        responsibilities: "Научные исследования",
        comment: "",
      },
    ] as Employment[],
    currentOrganization: "Научно-исследовательский институт",
    currentPosition: "Научный сотрудник",
    notes: [
      {
        id: generateId(),
        content: "Ученый, работает в НИИ",
        type: "general",
        createdById: "user_019",
        isPinned: false,
        tags: ["science", "research"],
      },
    ] as Note[],
    maritalStatus: "single",
    hasChildren: false,
    childrenCount: 0,
    isPensioner: false,
    isDisabled: false,
    status: "active",
    category: "individual",
    isVIP: false,
    isBlacklisted: false,
    responsibleUserId: "user_019",
    responsibleUserName: "Менеджер Дмитрий",
    departmentName: "Отдел работы с клиентами",
    comment: "",
    tags: ["science", "active", "research"],
  },

  {
    id: "cit_019",
    createdAt: "2023-02-05T12:45:00Z",
    updatedAt: "2024-01-07T10:00:00Z",
    lastName: "Григорьев",
    firstName: "Роман",
    middleName: "Петрович",
    fullName: "Григорьев Роман Петрович",
    dateOfBirth: "1989-11-03",
    placeOfBirth: "г. Хабаровск",
    gender: "male",
    age: calculateAge("1989-11-03"),
    inn: "270901234567",
    snils: "901-234-567 80",
    citizenship: "Российская Федерация",
    addresses: [
      {
        id: generateId(),
        type: "registration",
        country: "Россия",
        region: "Хабаровский край",
        city: "Хабаровск",
        district: "Центральный",
        street: "ул. Муравьева-Амурского",
        building: "25",
        apartment: "12",
        postalCode: "680000",
        isActual: true,
        comment: "",
      },
    ] as Address[],
    phones: [{ id: generateId(), type: "mobile", value: "+7 (908) 901-23-45", isPrimary: true, isVerified: true, comment: "" }] as Phone[],
    emails: [{ id: generateId(), type: "personal", value: "r.grigoriev@yandex.ru", isPrimary: true, isVerified: true, comment: "" }] as Email[],
    preferredContactMethod: "phone",
    educationLevel: "bachelor",
    educations: [
      {
        id: generateId(),
        level: "bachelor",
        institutionName: "Хабаровский Государственный Университет Экономики и Права",
        institutionType: "university",
        faculty: "Экономический",
        specialty: "Менеджмент",
        qualification: "Бакалавр менеджмента",
        startDate: "2007-09-01",
        endDate: "2011-06-30",
        documentNumber: "456789",
        documentDate: "2011-06-30",
        isCurrent: false,
        comment: "",
      },
    ] as Education[],
    employmentType: "full_time",
    employments: [
      {
        id: generateId(),
        organizationName: 'ООО "ДальВостТорг"',
        organizationInn: "2701234567",
        position: "Коммерческий директор",
        department: "Руководство",
        employmentType: "full_time",
        startDate: "2015-03-01",
        isCurrent: true,
        salary: 180000,
        currency: "RUB",
        workSchedule: "full",
        address: "г. Хабаровск, ул. Амурский бульвар, 30",
        supervisorName: "",
        supervisorPhone: "",
        responsibilities: "Управление коммерческой деятельностью",
        comment: "",
      },
    ] as Employment[],
    currentOrganization: 'ООО "ДальВостТорг"',
    currentPosition: "Коммерческий директор",
    notes: [
      {
        id: generateId(),
        content: "Руководитель высшего звена",
        type: "important",
        createdById: "user_020",
        isPinned: true,
        tags: ["executive", "vip"],
      },
    ] as Note[],
    maritalStatus: "married",
    hasChildren: true,
    childrenCount: 2,
    isPensioner: false,
    isDisabled: false,
    status: "active",
    category: "individual",
    isVIP: true,
    isBlacklisted: false,
    responsibleUserId: "user_020",
    responsibleUserName: "Менеджер Елена",
    departmentName: "Отдел работы с VIP клиентами",
    comment: "VIP клиент, коммерческий директор",
    tags: ["vip", "executive", "active"],
  },

  {
    id: "cit_020",
    createdAt: "2023-05-22T08:15:00Z",
    updatedAt: "2024-01-06T14:45:00Z",
    lastName: "Егорова",
    firstName: "Татьяна",
    middleName: "Николаевна",
    fullName: "Егорова Татьяна Николаевна",
    dateOfBirth: "1994-09-17",
    placeOfBirth: "г. Владивосток",
    gender: "female",
    age: calculateAge("1994-09-17"),
    inn: "250012345678",
    snils: "012-345-678 91",
    citizenship: "Российская Федерация",
    addresses: [
      {
        id: generateId(),
        type: "registration",
        country: "Россия",
        region: "Приморский край",
        city: "Владивосток",
        district: "Первомайский",
        street: "Светланская улица",
        building: "55",
        apartment: "33",
        postalCode: "690000",
        isActual: true,
        comment: "",
      },
    ] as Address[],
    phones: [{ id: generateId(), type: "mobile", value: "+7 (909) 012-34-56", isPrimary: true, isVerified: true, comment: "" }] as Phone[],
    emails: [{ id: generateId(), type: "personal", value: "t.egorova@gmail.com", isPrimary: true, isVerified: true, comment: "" }] as Email[],
    preferredContactMethod: "messenger",
    educationLevel: "bachelor",
    educations: [
      {
        id: generateId(),
        level: "bachelor",
        institutionName: "Дальневосточный Федеральный Университет",
        institutionType: "university",
        faculty: "Инженерная школа",
        specialty: "Логистика",
        qualification: "Бакалавр",
        startDate: "2012-09-01",
        endDate: "2016-06-30",
        documentNumber: "567890",
        documentDate: "2016-06-30",
        isCurrent: false,
        comment: "",
      },
    ] as Education[],
    employmentType: "full_time",
    employments: [
      {
        id: generateId(),
        organizationName: 'ООО "ДальЛогистик"',
        organizationInn: "2501234567",
        position: "Логист",
        department: "Отдел логистики",
        employmentType: "full_time",
        startDate: "2016-09-01",
        isCurrent: true,
        salary: 75000,
        currency: "RUB",
        workSchedule: "full",
        address: "г. Владивосток, ул. Некрасовская, 45",
        supervisorName: "Петров П.П.",
        supervisorPhone: "+7 (423) 222-33-44",
        responsibilities: "Организация грузоперевозок",
        comment: "",
      },
    ] as Employment[],
    currentOrganization: 'ООО "ДальЛогистик"',
    currentPosition: "Логист",
    notes: [
      { id: generateId(), content: "Специалист по логистике", type: "general", createdById: "user_021", isPinned: false, tags: ["logistics"] },
    ] as Note[],
    maritalStatus: "single",
    hasChildren: false,
    childrenCount: 0,
    isPensioner: false,
    isDisabled: false,
    status: "active",
    category: "individual",
    isVIP: false,
    isBlacklisted: false,
    responsibleUserId: "user_021",
    responsibleUserName: "Менеджер Виктор",
    departmentName: "Отдел работы с клиентами",
    comment: "",
    tags: ["logistics", "active"],
  },

  {
    id: "cit_021",
    createdAt: "2023-08-15T11:30:00Z",
    updatedAt: "2024-01-05T09:00:00Z",
    lastName: "Титов",
    firstName: "Евгений",
    middleName: "Александрович",
    fullName: "Титов Евгений Александрович",
    dateOfBirth: "1972-04-25",
    placeOfBirth: "г. Ярославль",
    gender: "male",
    age: calculateAge("1972-04-25"),
    inn: "760123456780",
    snils: "123-456-780 02",
    citizenship: "Российская Федерация",
    addresses: [
      {
        id: generateId(),
        type: "registration",
        country: "Россия",
        region: "Ярославская область",
        city: "Ярославль",
        district: "Кировский",
        street: "ул. Советская",
        building: "60",
        apartment: "45",
        postalCode: "150000",
        isActual: true,
        comment: "",
      },
    ] as Address[],
    phones: [{ id: generateId(), type: "mobile", value: "+7 (910) 123-45-67", isPrimary: true, isVerified: true, comment: "" }] as Phone[],
    emails: [{ id: generateId(), type: "personal", value: "e.titov@mail.ru", isPrimary: true, isVerified: true, comment: "" }] as Email[],
    preferredContactMethod: "phone",
    educationLevel: "vocational",
    educations: [
      {
        id: generateId(),
        level: "vocational",
        institutionName: "Ярославский Автомеханический Колледж",
        institutionType: "college",
        faculty: "",
        specialty: "Автомеханик",
        qualification: "Среднее специальное",
        startDate: "1989-09-01",
        endDate: "1992-06-30",
        documentNumber: "678901",
        documentDate: "1992-06-30",
        isCurrent: false,
        comment: "",
      },
    ] as Education[],
    employmentType: "self_employed",
    employments: [
      {
        id: generateId(),
        organizationName: "ИП Титов Е.А.",
        organizationInn: "760123456780",
        position: "Индивидуальный предприниматель",
        department: "",
        employmentType: "self_employed",
        startDate: "2000-01-01",
        isCurrent: true,
        salary: 150000,
        currency: "RUB",
        workSchedule: "full",
        address: "г. Ярославль, ул. Свободы, 80",
        supervisorName: "",
        supervisorPhone: "",
        responsibilities: "Ремонт автомобилей",
        comment: "Владелец СТО",
      },
    ] as Employment[],
    currentOrganization: "ИП Титов Е.А.",
    currentPosition: "Индивидуальный предприниматель",
    notes: [
      {
        id: generateId(),
        content: "Владелец автосервиса",
        type: "general",
        createdById: "user_022",
        isPinned: false,
        tags: ["entrepreneur", "auto"],
      },
    ] as Note[],
    maritalStatus: "married",
    hasChildren: true,
    childrenCount: 2,
    isPensioner: false,
    isDisabled: false,
    status: "active",
    category: "entrepreneur",
    isVIP: false,
    isBlacklisted: false,
    responsibleUserId: "user_022",
    responsibleUserName: "Менеджер Наталья",
    departmentName: "Отдел работы с партнерами",
    comment: "",
    tags: ["entrepreneur", "active", "auto"],
  },

  {
    id: "cit_022",
    createdAt: "2023-10-18T13:00:00Z",
    updatedAt: "2024-01-04T16:15:00Z",
    lastName: "Белова",
    firstName: "Вероника",
    middleName: "Сергеевна",
    fullName: "Белова Вероника Сергеевна",
    dateOfBirth: "1997-06-12",
    placeOfBirth: "г. Томск",
    gender: "female",
    age: calculateAge("1997-06-12"),
    inn: "700234567891",
    snils: "234-567-891 13",
    citizenship: "Российская Федерация",
    addresses: [
      {
        id: generateId(),
        type: "registration",
        country: "Россия",
        region: "Томская область",
        city: "Томск",
        district: "Советский",
        street: "пр. Ленина",
        building: "85",
        apartment: "60",
        postalCode: "634000",
        isActual: true,
        comment: "",
      },
    ] as Address[],
    phones: [{ id: generateId(), type: "mobile", value: "+7 (911) 234-56-78", isPrimary: true, isVerified: true, comment: "" }] as Phone[],
    emails: [{ id: generateId(), type: "personal", value: "v.belova@yandex.ru", isPrimary: true, isVerified: true, comment: "" }] as Email[],
    preferredContactMethod: "email",
    educationLevel: "bachelor",
    educations: [
      {
        id: generateId(),
        level: "bachelor",
        institutionName: "Томский Государственный Университет",
        institutionType: "university",
        faculty: "Физический",
        specialty: "Физика",
        qualification: "Бакалавр физики",
        startDate: "2015-09-01",
        endDate: "2019-06-30",
        documentNumber: "789012",
        documentDate: "2019-06-30",
        isCurrent: false,
        comment: "",
      },
    ] as Education[],
    employmentType: "student",
    employments: [],
    currentOrganization: "",
    currentPosition: "Студент",
    notes: [
      {
        id: generateId(),
        content: "Студент, продолжает обучение",
        type: "general",
        createdById: "user_023",
        isPinned: false,
        tags: ["student", "young"],
      },
    ] as Note[],
    maritalStatus: "single",
    hasChildren: false,
    childrenCount: 0,
    isPensioner: false,
    isDisabled: false,
    status: "pending",
    category: "individual",
    isVIP: false,
    isBlacklisted: false,
    responsibleUserId: "user_023",
    responsibleUserName: "Менеджер Ольга",
    departmentName: "Отдел работы с клиентами",
    comment: "Студент, перспективный молодой специалист",
    tags: ["student", "young", "pending"],
  },

  {
    id: "cit_023",
    createdAt: "2023-01-05T10:00:00Z",
    updatedAt: "2024-01-03T12:30:00Z",
    lastName: "Жуков",
    firstName: "Игорь",
    middleName: "Владимирович",
    fullName: "Жуков Игорь Владимирович",
    dateOfBirth: "1960-12-01",
    placeOfBirth: "г. Тула",
    gender: "male",
    age: calculateAge("1960-12-01"),
    inn: "710345678902",
    snils: "345-678-902 24",
    citizenship: "Российская Федерация",
    addresses: [
      {
        id: generateId(),
        type: "registration",
        country: "Россия",
        region: "Тульская область",
        city: "Тула",
        district: "Привокзальный",
        street: "ул. Кирова",
        building: "45",
        apartment: "20",
        postalCode: "300000",
        isActual: true,
        comment: "",
      },
    ] as Address[],
    phones: [{ id: generateId(), type: "mobile", value: "+7 (912) 345-67-89", isPrimary: true, isVerified: true, comment: "" }] as Phone[],
    emails: [{ id: generateId(), type: "personal", value: "i.zhukov@mail.ru", isPrimary: true, isVerified: false, comment: "" }] as Email[],
    preferredContactMethod: "phone",
    educationLevel: "secondary",
    educations: [
      {
        id: generateId(),
        level: "secondary",
        institutionName: "Средняя школа №15",
        institutionType: "school",
        faculty: "",
        specialty: "",
        qualification: "Среднее образование",
        startDate: "1967-09-01",
        endDate: "1977-06-30",
        documentNumber: "890123",
        documentDate: "1977-06-30",
        isCurrent: false,
        comment: "",
      },
    ] as Education[],
    employmentType: "pensioner",
    employments: [
      {
        id: generateId(),
        organizationName: "Тульский Оружейный Завод",
        organizationInn: "7101234567",
        position: "Токарь",
        department: "Производственный цех",
        employmentType: "full_time",
        startDate: "1978-03-01",
        endDate: "2010-12-01",
        isCurrent: false,
        salary: 40000,
        currency: "RUB",
        workSchedule: "full",
        address: "г. Тула, ул. Октябрьская, 50",
        supervisorName: "Иванов И.И.",
        supervisorPhone: "+7 (4872) 333-44-55",
        responsibilities: "Обработка деталей",
        comment: "Вышел на пенсию по возрасту",
      },
    ] as Employment[],
    currentOrganization: "",
    currentPosition: "Пенсионер",
    notes: [
      {
        id: generateId(),
        content: "Пенсионер, ветеран предприятия",
        type: "important",
        createdById: "user_024",
        isPinned: true,
        tags: ["pensioner", "veteran"],
      },
    ] as Note[],
    maritalStatus: "widowed",
    hasChildren: true,
    childrenCount: 2,
    isPensioner: true,
    isDisabled: true,
    disabilityGroup: "3",
    status: "active",
    category: "individual",
    isVIP: false,
    isBlacklisted: false,
    responsibleUserId: "user_024",
    responsibleUserName: "Менеджер Татьяна",
    departmentName: "Отдел социальной поддержки",
    comment: "Ветеран труда, нуждается в поддержке",
    tags: ["pensioner", "veteran", "disabled", "social"],
  },

  {
    id: "cit_024",
    createdAt: "2023-12-01T14:30:00Z",
    updatedAt: "2024-01-26T11:00:00Z",
    lastName: "Виноградова",
    firstName: "Алина",
    middleName: "Дмитриевна",
    fullName: "Виноградова Алина Дмитриевна",
    dateOfBirth: "1999-03-08",
    placeOfBirth: "г. Сочи",
    gender: "female",
    age: calculateAge("1999-03-08"),
    inn: "230456789013",
    snils: "456-789-013 35",
    citizenship: "Российская Федерация",
    addresses: [
      {
        id: generateId(),
        type: "registration",
        country: "Россия",
        region: "Краснодарский край",
        city: "Сочи",
        district: "Центральный",
        street: "ул. Навагинская",
        building: "15",
        apartment: "8",
        postalCode: "354000",
        isActual: true,
        comment: "",
      },
    ] as Address[],
    phones: [{ id: generateId(), type: "mobile", value: "+7 (913) 456-78-90", isPrimary: true, isVerified: true, comment: "" }] as Phone[],
    emails: [{ id: generateId(), type: "personal", value: "a.vinogradova@gmail.com", isPrimary: true, isVerified: true, comment: "" }] as Email[],
    preferredContactMethod: "messenger",
    educationLevel: "bachelor",
    educations: [
      {
        id: generateId(),
        level: "bachelor",
        institutionName: "Сочинский Государственный Университет",
        institutionType: "university",
        faculty: "Сервиса и туризма",
        specialty: "Туризм",
        qualification: "Бакалавр",
        startDate: "2017-09-01",
        endDate: "2021-06-30",
        documentNumber: "901234",
        documentDate: "2021-06-30",
        isCurrent: false,
        comment: "",
      },
    ] as Education[],
    employmentType: "full_time",
    employments: [
      {
        id: generateId(),
        organizationName: 'Отель "Жемчужина"',
        organizationInn: "2301234567",
        position: "Администратор",
        department: "Служба приема",
        employmentType: "full_time",
        startDate: "2021-09-01",
        isCurrent: true,
        salary: 50000,
        currency: "RUB",
        workSchedule: "shift",
        address: "г. Сочи, Курортный проспект, 105",
        supervisorName: "Петрова П.П.",
        supervisorPhone: "+7 (8622) 444-55-66",
        responsibilities: "Прием гостей, бронирование",
        comment: "",
      },
    ] as Employment[],
    currentOrganization: 'Отель "Жемчужина"',
    currentPosition: "Администратор",
    notes: [
      {
        id: generateId(),
        content: "Работает в сфере туризма",
        type: "general",
        createdById: "user_025",
        isPinned: false,
        tags: ["tourism", "hospitality"],
      },
    ] as Note[],
    maritalStatus: "single",
    hasChildren: false,
    childrenCount: 0,
    isPensioner: false,
    isDisabled: false,
    status: "active",
    category: "individual",
    isVIP: false,
    isBlacklisted: false,
    responsibleUserId: "user_025",
    responsibleUserName: "Менеджер Андрей",
    departmentName: "Отдел работы с клиентами",
    comment: "",
    tags: ["tourism", "young", "active"],
  },

  {
    id: "cit_025",
    createdAt: "2023-04-08T09:00:00Z",
    updatedAt: "2024-01-02T15:30:00Z",
    lastName: "Медведев",
    firstName: "Павел",
    middleName: "Олегович",
    fullName: "Медведев Павел Олегович",
    dateOfBirth: "1984-07-20",
    placeOfBirth: "г. Калининград",
    gender: "male",
    age: calculateAge("1984-07-20"),
    inn: "390567890124",
    snils: "567-890-124 46",
    citizenship: "Российская Федерация",
    addresses: [
      {
        id: generateId(),
        type: "registration",
        country: "Россия",
        region: "Калининградская область",
        city: "Калининград",
        district: "Московский",
        street: "пр. Мира",
        building: "100",
        apartment: "75",
        postalCode: "236000",
        isActual: true,
        comment: "",
      },
    ] as Address[],
    phones: [{ id: generateId(), type: "mobile", value: "+7 (914) 567-89-01", isPrimary: true, isVerified: true, comment: "" }] as Phone[],
    emails: [{ id: generateId(), type: "personal", value: "p.medvedev@yandex.ru", isPrimary: true, isVerified: true, comment: "" }] as Email[],
    preferredContactMethod: "phone",
    educationLevel: "master",
    educations: [
      {
        id: generateId(),
        level: "bachelor",
        institutionName: "Балтийский Федеральный Университет",
        institutionType: "university",
        faculty: "Экономический",
        specialty: "Внешнеэкономическая деятельность",
        qualification: "Бакалавр экономики",
        startDate: "2002-09-01",
        endDate: "2006-06-30",
        documentNumber: "012345",
        documentDate: "2006-06-30",
        isCurrent: false,
        comment: "",
      },
      {
        id: generateId(),
        level: "master",
        institutionName: "Балтийский Федеральный Университет",
        institutionType: "university",
        faculty: "Экономический",
        specialty: "Международный бизнес",
        qualification: "Магистр экономики",
        startDate: "2006-09-01",
        endDate: "2008-06-30",
        documentNumber: "123456",
        documentDate: "2008-06-30",
        isCurrent: false,
        comment: "",
      },
    ] as Education[],
    employmentType: "full_time",
    employments: [
      {
        id: generateId(),
        organizationName: 'ООО "БалтИмпорт"',
        organizationInn: "3901234567",
        position: "Директор по ВЭД",
        department: "Руководство",
        employmentType: "full_time",
        startDate: "2012-05-01",
        isCurrent: true,
        salary: 200000,
        currency: "RUB",
        workSchedule: "full",
        address: "г. Калининград, ул. Театральная, 35",
        supervisorName: "",
        supervisorPhone: "",
        responsibilities: "Управление внешнеэкономической деятельностью",
        comment: "",
      },
    ] as Employment[],
    currentOrganization: 'ООО "БалтИмпорт"',
    currentPosition: "Директор по ВЭД",
    notes: [
      {
        id: generateId(),
        content: "Руководитель, специалист по ВЭД",
        type: "important",
        createdById: "user_026",
        isPinned: true,
        tags: ["executive", "ved"],
      },
    ] as Note[],
    maritalStatus: "married",
    hasChildren: true,
    childrenCount: 2,
    isPensioner: false,
    isDisabled: false,
    status: "active",
    category: "individual",
    isVIP: true,
    isBlacklisted: false,
    responsibleUserId: "user_026",
    responsibleUserName: "Менеджер Юлия",
    departmentName: "Отдел работы с VIP клиентами",
    comment: "VIP клиент, директор по ВЭД",
    tags: ["vip", "executive", "active", "ved"],
  },
];

// export const getCitizenById = (id: string): Citizen | undefined => {
//   return CITIZEN_MOCK_DATA.find(citizen => citizen.id === id);
// };

// export const getCitizensByFilter = (filters: {
//   search?: string;
//   status?: string[];
//   gender?: string[];
//   city?: string[];
//   employmentType?: string[];
//   educationLevel?: string[];
//   isVIP?: boolean;
//   hasChildren?: boolean;
// }): Citizen[] => {
//   return CITIZEN_MOCK_DATA.filter(citizen => {
//     if (filters.search) {
//       const searchLower = filters.search.toLowerCase();
//       const matchesName = citizen.fullName.toLowerCase().includes(searchLower);
//       const matchesInn = citizen.inn?.includes(searchLower);
//       const matchesEmail = citizen.emails.some(e => e.value.toLowerCase().includes(searchLower));
//       if (!matchesName && !matchesInn && !matchesEmail) return false;
//     }
//     if (filters.status && filters.status.length > 0) {
//       if (!filters.status.includes(citizen.status)) return false;
//     }
//     if (filters.gender && filters.gender.length > 0) {
//       if (!filters.gender.includes(citizen.gender)) return false;
//     }
//     if (filters.city && filters.city.length > 0) {
//       const citizenCities = citizen.addresses.map(a => a.city.toLowerCase());
//       if (!filters.city.some(c => citizenCities.some(cc => cc.includes(c.toLowerCase())))) return false;
//     }
//     if (filters.employmentType && filters.employmentType.length > 0) {
//       if (!filters.employmentType.includes(citizen.employmentType)) return false;
//     }
//     if (filters.educationLevel && filters.educationLevel.length > 0) {
//       if (!filters.educationLevel.includes(citizen.educationLevel)) return false;
//     }
//     if (filters.isVIP !== undefined) {
//       if (citizen.isVIP !== filters.isVIP) return false;
//     }
//     if (filters.hasChildren !== undefined) {
//       if (citizen.hasChildren !== filters.hasChildren) return false;
//     }
//     return true;
//   });
// };

// export const getTotalCitizensCount = (): number => {
//   return CITIZEN_MOCK_DATA.length;
// };

// export const getCitizensByStatus = (status: string): Citizen[] => {
//   return CITIZEN_MOCK_DATA.filter(citizen => citizen.status === status);
// };

// export const getCitizensByGender = (gender: string): Citizen[] => {
//   return CITIZEN_MOCK_DATA.filter(citizen => citizen.gender === gender);
// };

// export const getVIPCitizens = (): Citizen[] => {
//   return CITIZEN_MOCK_DATA.filter(citizen => citizen.isVIP);
// };

// export const getPensionerCitizens = (): Citizen[] => {
//   return CITIZEN_MOCK_DATA.filter(citizen => citizen.isPensioner);
// };

// export const getCitizensByCity = (city: string): Citizen[] => {
//   return CITIZEN_MOCK_DATA.filter(citizen =>
//     citizen.addresses.some(a => a.city.toLowerCase() === city.toLowerCase())
//   );
// };

// export const getStatistics = () => {
//   const total = CITIZEN_MOCK_DATA.length;
//   const byGender = {
//     male: CITIZEN_MOCK_DATA.filter(c => c.gender === 'male').length,
//     female: CITIZEN_MOCK_DATA.filter(c => c.gender === 'female').length,
//   };
//   const byStatus = {
//     active: CITIZEN_MOCK_DATA.filter(c => c.status === 'active').length,
//     archived: CITIZEN_MOCK_DATA.filter(c => c.status === 'archived').length,
//     pending: CITIZEN_MOCK_DATA.filter(c => c.status === 'pending').length,
//     blocked: CITIZEN_MOCK_DATA.filter(c => c.status === 'blocked').length,
//   };
//   const byEmployment = {
//     full_time: CITIZEN_MOCK_DATA.filter(c => c.employmentType === 'full_time').length,
//     part_time: CITIZEN_MOCK_DATA.filter(c => c.employmentType === 'part_time').length,
//     self_employed: CITIZEN_MOCK_DATA.filter(c => c.employmentType === 'self_employed').length,
//     unemployed: CITIZEN_MOCK_DATA.filter(c => c.employmentType === 'unemployed').length,
//     pensioner: CITIZEN_MOCK_DATA.filter(c => c.employmentType === 'pensioner').length,
//     student: CITIZEN_MOCK_DATA.filter(c => c.employmentType === 'student').length,
//   };
//   const byEducation = {
//     secondary: CITIZEN_MOCK_DATA.filter(c => c.educationLevel === 'secondary').length,
//     vocational: CITIZEN_MOCK_DATA.filter(c => c.educationLevel === 'vocational').length,
//     bachelor: CITIZEN_MOCK_DATA.filter(c => c.educationLevel === 'bachelor').length,
//     master: CITIZEN_MOCK_DATA.filter(c => c.educationLevel === 'master').length,
//     postgraduate: CITIZEN_MOCK_DATA.filter(c => c.educationLevel === 'postgraduate').length,
//   };
//   const vipCount = CITIZEN_MOCK_DATA.filter(c => c.isVIP).length;
//   const withChildren = CITIZEN_MOCK_DATA.filter(c => c.hasChildren).length;
//   const avgAge = Math.round(CITIZEN_MOCK_DATA.reduce((sum, c) => sum + c.age, 0) / total);

//   return {
//     total,
//     byGender,
//     byStatus,
//     byEmployment,
//     byEducation,
//     vipCount,
//     withChildren,
//     avgAge,
//   };
// };
